apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: map-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: map-service
    app.kubernetes.io/part-of: nyc-transit
  name: map-service
  namespace: jduimovich
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: map-service
status:
  loadBalancer: {}
